[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "123456"
database = "go-excel-exporter"
maxOpenConn = 50
maxIdleConn = 5
timeout = 10 #second

[log]
logPath = "/gowork/go-excel-exporter/runtime" #日志文件路径
maxSize = 500 #单个文件最大size，单位MB
maxBackups = 100 #最大过期日志保留的个数
maxAge = 30 #保留过期文件的最大时间间隔,单位是天
compress = false #是否需要压缩滚动日志, 使用的 gzip 压缩

[system]
downloadPath = "/gowork/go-excel-exporter/download" #下载文件存储的目录
domain = "http://localhost:8080" # 访问下载文件的域名